version: '2'
services:
  odoo:
    image: akretion/voodoo:latest
    labels:
      main_service: "True"
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        - UID = 1001
        - GID = 1001
